services:
  caddy:
    container_name: scrape_space_caddy
    platform: linux/arm64
    image: caddy:latest
    restart: always
    ports:
      - 9999:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frontend/dist:/var/www:ro

  backend:
    container_name: scrape_space_backend
    platform: linux/arm64
    build: ./backend
    restart: always
    expose:
      - 8080

  mongodb:
    image: mongodb/mongodb-community-server:latest
    platform: linux/arm64
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: